### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman#1]
In chapter 2, I see there's a `<em><b>Homunculus`. But, the style result is that it's not italicized. I see it's italicized in print.

In chapter-4-1.xhtml line 17 there's an extra-indented paragraph. That `<span>` doesn't need to be there. `<span>` is our house semantic for "a line of poetry/verse". In this case it's not verse, it's just a line, so we can pull that i1 class into the `<p> `tag and remove the span. I imagine you'll have to slightly tweak the CSS too. If this occurs elsewhere in the book (outside of actual verse) then let's update those too. I see this also appears in at least chapter-7-32 and 8-31.

Related, I see there's an "indent" class with 25% indent. This can be a lot on big screens. Maybe a fixed number of ems might be a better choice?

For the CSS on local.css line 366, that's a great way of duplicating the layout we want. But if the ereader doesn't support flex then it falls back to an inline series of ***. Can we style the default to try to emulate the page? Maybe display: table/table-cell? I think many ereaders support that, even if they don't support display: flex.

In chapter-7-10, the table is italicized and thus the noteref is also in italics. But I think it should probably be without italics. Would it be sane to to target that with CSS?

In chapter-7-26 I see there's an invisible span. I think you put it there to align the following paragraph so that it appears after the above line. But, in FF it doesn't seem to strictly align for some reason. I wonder if this can be solved in some way that doesn't involve duplicating text in the prose? Maybe a ::before element with display: inline, content: ('the sentence...'), visibility: hidden?

**Comment by robinwhittleton** [comment]
Fixed these in the latest set of commits, thanks for the review.

For the noteref styling, would it be better to add that into core? If so then it can be dropped from here afterwards.

**Comment by acabal** [comment]
Yikes, didn't realize I forgot to escape that HTML. I just edited the post, hopefully it's readable now!

**Comment by robinwhittleton** [comment]
I think I got the gist anyway 🙂

**Comment by acabal** [comment]
We could put a noteref/italics rule in core.css, though it won't cover the truly general case because italics can come from any CSS and not just `<i>` or `<em>`. But it might be worth it to do it anyway.

**Comment by robinwhittleton** [comment]
Updated core.css with the new endnote reference style. I think that’s it!
